# Generated by Django 5.0.3 on 2024-05-28 00:05

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0002_alter_matricula_numero_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=250)),
                ('descricao', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_chegada', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('aula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.aula')),
                ('estudante_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estudante.matricula')),
            ],
        ),
    ]
