# Generated by Django 5.0.2 on 2024-06-09 17:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0003_aula_presenca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('data_fim', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='data_aula',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aula',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estudante.turma'),
        ),
    ]
