# Generated by Django 5.0.2 on 2024-06-09 18:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0005_turma_data_inclusao_alter_turma_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='data_inclusao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
