# Generated by Django 5.0.2 on 2024-06-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0006_alter_turma_data_inclusao_alter_turma_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
