# Generated by Django 5.0.2 on 2024-06-14 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0008_matricula_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='data_inclusao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='data_hora_chegada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
