# Generated by Django 5.0.2 on 2024-07-16 01:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0010_alter_turma_data_inclusao'),
        ('pessoa', '0014_tipo_pessoa_alter_documento_tipo_documento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cbo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, null=True)),
                ('carga_horaria_aula', models.TimeField(blank=True, null=True)),
                ('data_inclusao', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aula',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='data_hora_chegada',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='estudante_id',
        ),
        migrations.AddField(
            model_name='aula',
            name='conteudo',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aula',
            name='educador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pessoa.pessoa'),
        ),
        migrations.AddField(
            model_name='aula',
            name='ocorrencias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presenca',
            name='matricula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estudante.matricula'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estudante.turma'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estudante.turma'),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='aula_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estudante.aula'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='cbo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estudante.cbo'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estudante.curso'),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('razao_social', models.CharField(max_length=255)),
                ('pessoa_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='matricula',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estudante.empresa'),
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estudante.curso')),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estudante.modulo'),
        ),
        migrations.AddField(
            model_name='presenca',
            name='tipo_presenca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estudante.tipo_presenca'),
        ),
    ]
