# Generated by Django 5.0.2 on 2024-07-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0011_cbo_curso_tipo_presenca_remove_aula_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='data_presenca',
            field=models.DateField(blank=True, null=True),
        ),
    ]
