# Generated by Django 5.0.2 on 2024-07-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0012_presenca_data_presenca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presenca',
            options={'verbose_name': 'Registro de presença', 'verbose_name_plural': 'Presenças'},
        ),
        migrations.AlterModelOptions(
            name='tipo_presenca',
            options={'verbose_name': 'Profissional interno', 'verbose_name_plural': 'Tipos de profissionais internos'},
        ),
    ]
