# Generated by Django 5.0.2 on 2024-07-30 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0014_escolaridade_matricula_escolaridade'),
        ('pessoa', '0017_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('seg', 'Segunda-feira'), ('ter', 'Terça-feira'), ('qua', 'Quarta-feira'), ('qui', 'Quinta-feira'), ('sex', 'Sexta-feira'), ('sab', 'Sábado'), ('dom', 'Domingo')], max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Psa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='documento',
            field=models.ManyToManyField(blank=True, related_name='empresas', to='pessoa.documento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='endereco',
            field=models.ManyToManyField(blank=True, related_name='empresas', to='pessoa.endereco'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='data_inicio_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='data_inicio_empresa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='data_terminio_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='data_terminio_empresa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='hora_fim_expediente',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='hora_inicio_expediente',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='salario',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Desligamentos_matriculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, null=True)),
                ('data_desligamento', models.DateField(blank=True, null=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estudante.matricula')),
                ('usuario_inclui', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Atividade_teorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.CharField(blank=True, max_length=10, null=True)),
                ('hora_termino', models.CharField(blank=True, max_length=10, null=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estudante.matricula')),
                ('dias_da_semana', models.ManyToManyField(to='estudante.diasemana')),
            ],
        ),
        migrations.AddField(
            model_name='matricula',
            name='dias_da_semana_curso',
            field=models.ManyToManyField(blank=True, null=True, related_name='matriculas_curso', to='estudante.diasemana'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='dias_da_semana_empresa',
            field=models.ManyToManyField(blank=True, null=True, related_name='matriculas_empresa', to='estudante.diasemana'),
        ),
        migrations.CreateModel(
            name='CBOAssociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associado_de', to='estudante.cbo')),
                ('cbo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associados', to='estudante.cbo')),
            ],
            options={
                'verbose_name': 'Associação de CBO',
                'verbose_name_plural': 'Associações de CBOs',
                'unique_together': {('cbo', 'associado')},
            },
        ),
    ]
