# Generated by Django 5.0.2 on 2024-07-30 16:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0015_diasemana_psa_empresa_documento_empresa_endereco_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Desligamentos_matriculas',
            new_name='Desligamento_matricula',
        ),
    ]
