# Generated by Django 5.0.2 on 2024-08-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0019_alter_matricula_salario'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='quantidade_meses_contrato',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
