# Generated by Django 5.0.2 on 2024-09-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0020_matricula_quantidade_meses_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='carga_horaria_aula',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
