# Generated by Django 5.0.2 on 2024-09-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0021_alter_curso_carga_horaria_aula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='dias_da_semana_curso',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='dias_da_semana_empresa',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='data_inicio',
        ),
        migrations.AddField(
            model_name='turma',
            name='dias_da_semana_curso',
            field=models.ManyToManyField(blank=True, null=True, related_name='matriculas_curso', to='estudante.diasemana'),
        ),
        migrations.AddField(
            model_name='turma',
            name='dias_da_semana_empresa',
            field=models.ManyToManyField(blank=True, null=True, related_name='matriculas_empresa', to='estudante.diasemana'),
        ),
    ]
