# Generated by Django 5.0.2 on 2024-09-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0023_curso_protocolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='hora_fim_encontro',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='hora_inicio_encontro',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
