# Generated by Django 5.0.2 on 2024-09-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0024_turma_hora_fim_encontro_turma_hora_inicio_encontro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade_teorica',
            name='dias_da_semana',
        ),
        migrations.AddField(
            model_name='atividade_teorica',
            name='qtd_encontros',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
