# Generated by Django 5.0.2 on 2024-09-21 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0026_rename_qtd_encontros_atividade_teorica_quantidade_de_encontros'),
        ('pessoa', '0018_alter_contato_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cboassociado',
            name='associado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='associado_de', to='estudante.cbo'),
        ),
        migrations.AlterField(
            model_name='cboassociado',
            name='cbo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='associados', to='estudante.cbo'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='pessoa_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pessoa.pessoa'),
        ),
    ]
