# Generated by Django 5.0.2 on 2024-09-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0027_alter_cboassociado_associado_alter_cboassociado_cbo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='ativades_praticas',
            field=models.CharField(blank=True, null=True),
        ),
    ]
