# Generated by Django 5.0.2 on 2024-09-21 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0028_matricula_ativades_praticas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='ativades_praticas',
            new_name='atividades_praticas',
        ),
    ]
