# Generated by Django 5.0.2 on 2024-10-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0029_rename_ativades_praticas_matricula_atividades_praticas'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='taxa_administrativa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
