# Generated by Django 5.0.2 on 2025-06-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0030_matricula_taxa_administrativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='valor_salario',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
