# Generated by Django 5.0.2 on 2025-06-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0031_matricula_valor_salario'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='data_fim_treinamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='data_inicio_treinamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='funcao_empresa',
            field=models.CharField(blank=True, null=True),
        ),
    ]
