# Generated by Django 5.0.2 on 2024-06-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('tipo_evento', models.CharField(choices=[('N', 'Criação de registro'), ('A', 'Alteração de registro'), ('R', 'Remoção de registro')], max_length=10)),
                ('model_afetada', models.CharField(max_length=50)),
                ('detalhes', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='acesso',
            name='user',
            field=models.CharField(),
        ),
    ]
