# Generated by Django 5.0.2 on 2024-03-17 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0004_contato_data_inclusao_endereco_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='data_alteracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='contato',
            field=models.ManyToManyField(null=True, to='pessoa.contato', verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.endereco', verbose_name='Endereco'),
        ),
    ]
