# Generated by Django 5.0.2 on 2024-03-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0005_contato_data_alteracao_alter_pessoa_contato_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relacao_familiar',
            new_name='Relacao',
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='contato',
            field=models.ManyToManyField(blank=True, null=True, to='pessoa.contato', verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
