# Generated by Django 5.0.3 on 2024-05-28 00:05

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0006_rename_relacao_familiar_relacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data_inclusao',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now),
        ),
        migrations.AlterField(
            model_name='documento',
            name='data_inclusao',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(choices=[('RG', 'Documento de identidade'), ('CPF', 'Cadastro de pessoa física'), ('CTPS', 'Carteira nacional de trabalho'), ('PASS', 'Passaporte'), ('CNH', 'Carteira de motorista'), ('EL', 'Título de eleitor'), ('CNS', 'Cartão nacional de saúde')], max_length=40),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='data_inclusao',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='contato',
            field=models.ManyToManyField(blank=True, to='pessoa.contato'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_inclusao',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.endereco'),
        ),
        migrations.AlterField(
            model_name='relacao',
            name='tipo_relacao',
            field=models.CharField(choices=[('PAI', 'Pai'), ('MÃE', 'Mãe'), ('FILHO', 'Filho'), ('FILHA', 'Filha'), ('IRMÃO', 'Irmão'), ('IRMÃ', 'Irmã'), ('AVÔ', 'Avô'), ('AVÓ', 'Avó'), ('TIO', 'Tio'), ('TIA', 'Tia'), ('PRIMO', 'Primo'), ('PRIMA', 'Prima'), ('SOGRO', 'Sogro'), ('SOGRA', 'Sogra'), ('GENRO', 'Genro'), ('NORA', 'Nora'), ('MARIDO', 'Marido'), ('ESPOSA', 'Esposa'), ('SOBRINHO', 'Sobrinho'), ('SOBRINHA', 'Sobrinha'), ('NETO', 'Neto'), ('NETA', 'Neta'), ('PAI_ADOTIVO', 'Pai Adotivo'), ('MÃE_ADOTIVA', 'Mãe Adotiva'), ('FILHO_ADOTIVO', 'Filho Adotivo'), ('FILHA_ADOTIVA', 'Filha Adotiva')], max_length=40),
        ),
    ]
