# Generated by Django 5.0.3 on 2024-05-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0007_alter_contato_data_inclusao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
