# Generated by Django 5.0.2 on 2024-05-29 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0008_endereco_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data_inclusao',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 31, 51, 57092, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='documento',
            name='data_inclusao',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 31, 51, 59086, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='data_inclusao',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 31, 51, 58091, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_inclusao',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 31, 51, 58091, tzinfo=datetime.timezone.utc)),
        ),
    ]
