# Generated by Django 5.0.2 on 2024-05-29 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0009_alter_contato_data_inclusao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data_inclusao',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 50, 56, 817844, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='documento',
            name='data_inclusao',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 50, 56, 818854, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='data_inclusao',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 50, 56, 817844, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_inclusao',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 50, 56, 817844, tzinfo=datetime.timezone.utc)),
        ),
    ]
