# Generated by Django 5.0.2 on 2024-05-29 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0011_alter_contato_data_inclusao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='documento',
            field=models.ManyToManyField(blank=True, to='pessoa.documento'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='data_inclusao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='documento',
            name='data_inclusao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='data_inclusao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_inclusao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
