# Generated by Django 5.0.2 on 2024-07-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0013_alter_pessoa_contato_alter_pessoa_documento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(choices=[('RG', 'Documento de identidade'), ('CPF', 'Cadastro de pessoa física'), ('CTPS', 'Carteira nacional de trabalho'), ('PASS', 'Passaporte'), ('CNH', 'Carteira de motorista'), ('EL', 'Título de eleitor'), ('CNS', 'Cartão nacional de saúde'), ('CNPJ', 'Cadastro Nacional da Pessoa Jurídica')], max_length=40),
        ),
        migrations.DeleteModel(
            name='Relacao',
        ),
    ]
