# Generated by Django 5.0.2 on 2024-07-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0014_tipo_pessoa_alter_documento_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='sexo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
