# Generated by Django 5.0.2 on 2024-07-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0015_pessoa_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
