# Generated by Django 5.0.2 on 2024-07-25 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0016_pessoa_foto_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard', models.BooleanField(default=True, help_text='O usuário pode acessar o dashboard?')),
                ('aprendizes', models.BooleanField(default=True, help_text='O usuário pode acessar a tela de listagem de aprendizes?')),
                ('matricular', models.BooleanField(default=True, help_text='O usuário pode matricular novos aprendizes?')),
                ('turmas', models.BooleanField(default=True, help_text='O usuário pode acessar a tela de listagem de turmas?')),
                ('diario_de_aula', models.BooleanField(default=True, help_text='O usuário pode acessar o diário de aulas?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
