# Generated by Django 5.0.2 on 2024-09-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0017_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
