# Generated by Django 5.0.2 on 2024-10-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0019_alter_pessoa_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='tipo_contato',
            field=models.CharField(choices=[('CELULAR', 'Celular'), ('CELULAR_2', 'Celular secundário'), ('TELEFONE', 'Telefone'), ('EMAIL', 'E-mail')], max_length=10),
        ),
    ]
