# Generated by Django 5.0.2 on 2025-06-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0022_alter_endereco_cep_alter_endereco_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='nro_documento',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='documento',
            field=models.ManyToManyField(blank=True, null=True, related_name='pessoas', to='pessoa.documento'),
        ),
    ]
